backend:
  name: github
  repo: tokura1222/music-platform
  branch: main
  base_url: https://pauth.vercel.app 

local_backend: true

media_folder: "public/music"
public_folder: "/music"

collections:
  - name: "data"
    label: "Data"
    files:
      - name: "songs"
        label: "Songs"
        file: "content/songs.json"
        description: "Manage your music library"
        fields:
          - label: "Songs List"
            name: "songs"
            widget: "list"
            fields:
              - {label: "ID", name: "id", widget: "uuid"}
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Artist", name: "artist", widget: "string"}
              - {label: "Audio File", name: "url", widget: "file"}
              - {label: "Cover Image", name: "coverPath", widget: "image", required: false}
              - {label: "Duration (Seconds)", name: "duration", widget: "number", value_type: "int", min: 0}
              - label: "Category"
                name: "category"
                widget: "select"
                options:
                  - {label: "Instrument", value: "instrument"}
                  - {label: "Reggae", value: "reggae"}
                  - {label: "Other", value: "other"}
                default: "other"
