backend:
  name: github
  repo: tokura1222/music-platform
  branch: main
  base_url: https://pauth.vercel.app 

local_backend: true

media_folder: "public/music"
public_folder: "/music"

collections:
  - name: "songs"
    label: "Songs"
    label_singular: "Song"
    folder: "content/songs"
    extension: "json"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    summary: "{{title}} - {{artist}} [{{category}}]"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Artist", name: "artist", widget: "string"}
      - {label: "Audio File", name: "url", widget: "file"}
      - {label: "Cover Image", name: "coverPath", widget: "image", required: false}
      - label: "Category"
        name: "category"
        widget: "select"
        options:
          - {label: "Instrument", value: "instrument"}
          - {label: "Reggae", value: "reggae"}
          - {label: "Other", value: "other"}
        default: "other"
